# Generated by Django 3.0.1 on 2020-02-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter book name.', max_length=100)),
                ('author', models.TextField(help_text='Enter author name.', max_length=50)),
                ('pages', models.TextField(help_text='Enter number of pages', max_length=5)),
                ('publisher', models.TextField(help_text='Enter publisher name', max_length=50)),
                ('pub_year', models.IntegerField(help_text='Enter year of publication')),
                ('hard_cover', models.ImageField(upload_to='static/images/')),
                ('size', models.TextField(help_text='Enter size book', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter price book', max_digits=10)),
                ('Discounts', models.DecimalField(decimal_places=2, help_text='Enter discounts', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter name Magazine', max_length=100)),
                ('pages', models.IntegerField(help_text='Enter count pages Magazine')),
                ('publisher', models.TextField(help_text='Enter publisher name', max_length=50)),
                ('pub_year', models.IntegerField(help_text='Enter year of publication')),
                ('numb', models.IntegerField(help_text='Enter number Magazine')),
                ('numb_in_year', models.IntegerField(help_text='Enter number Magazine')),
                ('size', models.TextField(help_text='Enter size book', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter price book', max_digits=10)),
                ('subs_price', models.DecimalField(decimal_places=2, help_text='Enter price book', max_digits=10)),
                ('Discounts', models.DecimalField(decimal_places=2, help_text='Enter discounts', max_digits=10)),
            ],
        ),
    ]
