# Generated by Django 3.0.3 on 2020-03-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter author name.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, help_text='Enter book genre.', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/books'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/magazine'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Discounts',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter discounts', max_digits=10),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='hard_cover',
            field=models.CharField(blank=True, help_text='Enter hard cover book (+/-)', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, help_text='Enter book name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.CharField(blank=True, help_text='Enter number of pages', max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter price book', max_digits=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.IntegerField(blank=True, help_text='Enter year of publication', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, help_text='Enter publisher name', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.CharField(blank=True, help_text='Enter size book', max_length=10),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='Discounts',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter discounts', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='name',
            field=models.CharField(blank=True, help_text='Enter name Magazine', max_length=100),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='numb',
            field=models.IntegerField(blank=True, help_text='Enter number Magazine', null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='numb_in_year',
            field=models.IntegerField(blank=True, help_text='Enter number Magazine', null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='pages',
            field=models.IntegerField(blank=True, help_text='Enter count pages Magazine', null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter price book', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='pub_year',
            field=models.IntegerField(blank=True, help_text='Enter year of publication', null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='publisher',
            field=models.CharField(blank=True, help_text='Enter publisher name', max_length=50),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='size',
            field=models.CharField(blank=True, help_text='Enter size book', max_length=10),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='subs_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter price book', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(null=True, to='store.BookGenre'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(null=True, to='store.BookAuthor'),
        ),
    ]
