# Generated by Django 3.0.1 on 2020-03-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='', help_text='Enter book genre.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='Enter author name.', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(help_text='Enter book name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.CharField(help_text='Enter number of pages', max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(help_text='Enter publisher name', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.CharField(help_text='Enter size book', max_length=10),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='name',
            field=models.CharField(help_text='Enter name Magazine', max_length=100),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='publisher',
            field=models.CharField(help_text='Enter publisher name', max_length=50),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='size',
            field=models.CharField(help_text='Enter size book', max_length=10),
        ),
    ]
