# Generated by Django 3.1rc1 on 2020-08-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200707_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, help_text='Enter book name.', max_length=100, verbose_name='Membership'),
        ),
    ]
