# Generated by Django 3.1rc1 on 2020-08-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200814_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Discounts',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter discounts', max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='store.BookAuthor', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='store.BookGenre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='hard_cover',
            field=models.CharField(blank=True, help_text='Enter hard cover book (+/-)', max_length=1, verbose_name='Твердая обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/books/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, help_text='Enter book name.', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.CharField(blank=True, help_text='Enter number of pages', max_length=5, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter price book', max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.IntegerField(blank=True, help_text='Enter year of publication', null=True, verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, help_text='Enter publisher name', max_length=50, verbose_name='Издатель'),
        ),
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.CharField(blank=True, help_text='Enter size book', max_length=10, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='name',
            field=models.CharField(blank=True, help_text='Enter author name.', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bookgenre',
            name='genre',
            field=models.CharField(blank=True, help_text='Enter book genre.', max_length=50, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='Discounts',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter discounts', max_digits=10, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/magazine', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='name',
            field=models.CharField(blank=True, help_text='Enter name Magazine', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='numb',
            field=models.IntegerField(blank=True, help_text='Enter number Magazine', null=True, verbose_name='Номер журнала'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='numb_in_year',
            field=models.IntegerField(blank=True, help_text='Enter number Magazine', null=True, verbose_name='Номер журнала в году'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='pages',
            field=models.IntegerField(blank=True, help_text='Enter count pages Magazine', null=True, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter price book', max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='pub_year',
            field=models.IntegerField(blank=True, help_text='Enter year of publication', null=True, verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='publisher',
            field=models.CharField(blank=True, help_text='Enter publisher name', max_length=50, verbose_name='Издатель'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='size',
            field=models.CharField(blank=True, help_text='Enter size book', max_length=10, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='subs_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter price book', max_digits=10, null=True, verbose_name='Цена подписки'),
        ),
    ]
