# Generated by Django 3.1.4 on 2021-02-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_categorydiscount_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydiscount',
            name='active',
            field=models.BooleanField(default=False, verbose_name='активация скидки'),
        ),
    ]
