# Generated by Django 3.1.4 on 2021-03-12 13:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_categorydiscount_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='publisher',
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.publisher'),
        ),
        migrations.AlterField(
            model_name='categorydiscount',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter discounts', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Discounts',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter discounts', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter price book', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
    ]
