# Generated by Django 3.1.4 on 2021-02-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='rating',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], help_text='Enter rating here', verbose_name='рейтинг продукта'),
        ),
    ]
