# Generated by Django 3.1rc1 on 2020-08-18 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter your name.', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Enter your last_name.', max_length=100, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, help_text='Enter your surname.', max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/avatar/', verbose_name='Изображение')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
