# Generated by Django 3.1rc1 on 2020-11-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201117_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, help_text='Количество товара', null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата покупки'),
        ),
    ]
